item {
  id: 1
  name: 'utility'
}

item {
  id: 2
  name: 'bottle'
}

item {
  id: 3
  name: 'cup'
}

item {
  id: 4
  name: 'fruit'
}

item {
  id: 5
  name: 'assemblyPart'
}

item {
  id: 6
  name: 'hammer'
}

item {
  id: 7
  name: 'scissors'
}

item {
  id: 8
  name: 'screwdriver'
}

item {
  id: 9
  name: 'tape'
}

item {
  id: 10
  name: 'toy'
}

item {
  id: 11
  name: 'tube'
}

item {
  id: 12
  name: 'wrench'
}

